version: "3.8"

services:
  library-sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: library-sqlserver
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=Davidivkovic2020
    ports:
      - "1433:1433"
    volumes: 
      - sql-data:/var/opt/mssql

volumes:
  sql-data: {}