const colors = require("tailwindcss/colors");

module.exports = {
  purge: ["./**/*.html", "./**/*.razor"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      screens: {
        "3xl": "1600px",
        "4xl": "1700px",
        "5xl": "1750px"
      },
      colors: {
        palegreen: "#52d246",
        bluegray: colors.blueGray,
        coolgray: colors.coolGray,
        truegray: colors.trueGray,
        warmgray: colors.warmGray,
        amber: colors.amber,
        lime: colors.lime,
        emerald: colors.emerald,
        teal: colors.teal,
        cyan: colors.cyan,
        lightblue: colors.lightBlue,
        violet: colors.violet,
        fuchsia: colors.fuchsia,
        pink: colors.pink,
        rose: colors.rose
      },
      spacing: {
        px: "1px",
        0: "0px",
        0.25: "0.075rem",
        0.5: "0.125rem",
        1: "0.25rem",
        1.25: "0.3125rem",
        1.5: "0.375rem",
        1.75: "0.4375rem",
        2: "0.5rem",
        2.5: "0.625rem",
        3: "0.75rem",
        3.25: "0.8125rem",
        3.5: "0.875rem",
        4: "1rem",
        5: "1.25rem",
        5.5: "1.375rem",
        6.5: "1.625rem"
      },
      fontSize: {
        xxxs: ["0.75rem", { lineHeight: "1rem" }],
        xxs: ["0.775rem", { lineHeight: "1rem" }],
        xs: ["0.8125rem", { lineHeight: "1.1rem" }],
        sm: ["0.875rem", { lineHeight: "1.25rem" }],
        md: ["0.9175rem", { lineHeight: "1.3rem" }],
        base: ["1rem", { lineHeight: "1.5rem" }],
        lg: ["1.125rem", { lineHeight: "1.75rem" }],
        xl: ["1.25rem", { lineHeight: "1.75rem" }],
        "2xl": ["1.5rem", { lineHeight: "2rem" }],
        "3xl": ["1.875rem", { lineHeight: "2.25rem" }],
        "4xl": ["2.25rem", { lineHeight: "2.5rem" }],
        "5xl": ["2.625rem", { lineHeight: "2.75rem" }],
        "6xl": ["3rem", { lineHeight: "1" }],
        "7xl": ["3.75rem", { lineHeight: "1" }],
        "8xl": ["4.5rem", { lineHeight: "1" }],
        "9xl": ["6rem", { lineHeight: "1" }],
        "10xl": ["8rem", { lineHeight: "1" }]
      }
    }
  },
  plugins: [],
  fontFamily: {
    sans: ["Inter", "sans-serif"]
  },
  variants: {
    accessibility: ["responsive", "hover", "focus-within", "focus"],
    alignContent: ["responsive", "hover"],
    alignItems: ["responsive", "hover"],
    alignSelf: ["responsive", "hover"],
    animation: ["responsive", "hover"],
    appearance: ["responsive", "hover"],
    backdropBlur: ["responsive", "hover"],
    backdropBrightness: ["responsive", "hover"],
    backdropContrast: ["responsive", "hover"],
    backdropDropShadow: ["responsive", "hover"],
    backdropFilter: ["responsive", "hover"],
    backdropGrayscale: ["responsive", "hover"],
    backdropHueRotate: ["responsive", "hover"],
    backdropInvert: ["responsive", "hover"],
    backdropSaturate: ["responsive", "hover"],
    backdropSepia: ["responsive", "hover"],
    backgroundAttachment: ["responsive", "hover"],
    backgroundBlendMode: ["responsive", "hover"],
    backgroundClip: ["responsive", "hover"],
    backgroundColor: ["responsive", "hover", "dark", "group-hover", "focus-within", "focus"],
    backgroundImage: ["responsive", "hover"],
    backgroundOpacity: ["responsive", "hover", "dark", "group-hover", "focus-within", "focus"],
    backgroundPosition: ["responsive", "hover"],
    backgroundRepeat: ["responsive", "hover"],
    backgroundSize: ["responsive", "hover"],
    blur: ["responsive", "hover"],
    borderCollapse: ["responsive", "hover"],
    borderColor: ["responsive", "hover", "dark", "group-hover", "focus-within", "focus"],
    borderOpacity: ["responsive", "hover", "dark", "group-hover", "focus-within", "focus"],
    borderRadius: ["responsive", "hover"],
    borderStyle: ["responsive", "hover"],
    borderWidth: ["responsive", "hover"],
    boxDecorationBreak: ["responsive", "hover"],
    boxShadow: ["responsive", "hover", "group-hover", "focus-within", "focus"],
    boxSizing: ["responsive", "hover"],
    brightness: ["responsive", "hover"],
    clear: ["responsive", "hover"],
    container: ["responsive", "hover"],
    contrast: ["responsive", "hover"],
    cursor: ["responsive", "hover"],
    display: ["responsive", "hover"],
    divideColor: ["responsive", "hover", "dark"],
    divideOpacity: ["responsive", "hover", "dark"],
    divideStyle: ["responsive", "hover"],
    divideWidth: ["responsive", "hover"],
    dropShadow: ["responsive", "hover"],
    fill: ["responsive", "hover"],
    filter: ["responsive", "hover"],
    flex: ["responsive", "hover"],
    flexDirection: ["responsive", "hover"],
    flexGrow: ["responsive", "hover"],
    flexShrink: ["responsive", "hover"],
    flexWrap: ["responsive", "hover"],
    float: ["responsive", "hover"],
    fontFamily: ["responsive", "hover"],
    fontSize: ["responsive", "hover"],
    fontSmoothing: ["responsive", "hover"],
    fontStyle: ["responsive", "hover"],
    fontVariantNumeric: ["responsive", "hover"],
    fontWeight: ["responsive", "hover"],
    gap: ["responsive", "hover"],
    gradientColorStops: ["responsive", "hover", "dark", "focus"],
    grayscale: ["responsive", "hover"],
    gridAutoColumns: ["responsive", "hover"],
    gridAutoFlow: ["responsive", "hover"],
    gridAutoRows: ["responsive", "hover"],
    gridColumn: ["responsive", "hover"],
    gridColumnEnd: ["responsive", "hover"],
    gridColumnStart: ["responsive", "hover"],
    gridRow: ["responsive", "hover"],
    gridRowEnd: ["responsive", "hover"],
    gridRowStart: ["responsive", "hover"],
    gridTemplateColumns: ["responsive", "hover"],
    gridTemplateRows: ["responsive", "hover"],
    height: ["responsive", "hover"],
    hueRotate: ["responsive", "hover"],
    inset: ["responsive", "hover"],
    invert: ["responsive", "hover"],
    isolation: ["responsive", "hover"],
    justifyContent: ["responsive", "hover"],
    justifyItems: ["responsive", "hover"],
    justifySelf: ["responsive", "hover"],
    letterSpacing: ["responsive", "hover"],
    lineHeight: ["responsive", "hover"],
    listStylePosition: ["responsive", "hover"],
    listStyleType: ["responsive", "hover"],
    margin: ["responsive", "hover"],
    maxHeight: ["responsive", "hover"],
    maxWidth: ["responsive", "hover"],
    minHeight: ["responsive", "hover"],
    minWidth: ["responsive", "hover"],
    mixBlendMode: ["responsive", "hover"],
    objectFit: ["responsive", "hover"],
    objectPosition: ["responsive", "hover"],
    opacity: ["responsive", "hover", "group-hover", "focus-within", "focus"],
    order: ["responsive", "hover"],
    outline: ["responsive", "hover", "focus-within", "focus"],
    overflow: ["responsive", "hover"],
    overscrollBehavior: ["responsive", "hover"],
    padding: ["responsive", "hover"],
    placeContent: ["responsive", "hover"],
    placeItems: ["responsive", "hover"],
    placeSelf: ["responsive", "hover"],
    placeholderColor: ["responsive", "hover", "dark", "focus"],
    placeholderOpacity: ["responsive", "hover", "dark", "focus"],
    pointerEvents: ["responsive", "hover"],
    position: ["responsive", "hover"],
    resize: ["responsive", "hover"],
    ringColor: ["responsive", "hover", "dark", "focus-within", "focus"],
    ringOffsetColor: ["responsive", "hover", "dark", "focus-within", "focus"],
    ringOffsetWidth: ["responsive", "hover", "focus-within", "focus"],
    ringOpacity: ["responsive", "hover", "dark", "focus-within", "focus"],
    ringWidth: ["responsive", "hover", "focus-within", "focus"],
    rotate: ["responsive", "hover", "focus"],
    saturate: ["responsive", "hover"],
    scale: ["responsive", "hover", "focus"],
    sepia: ["responsive", "hover"],
    skew: ["responsive", "hover", "focus"],
    space: ["responsive", "hover"],
    stroke: ["responsive", "hover"],
    strokeWidth: ["responsive", "hover"],
    tableLayout: ["responsive", "hover"],
    textAlign: ["responsive", "hover"],
    textColor: ["responsive", "hover", "dark", "group-hover", "focus-within", "focus"],
    textDecoration: ["responsive", "hover", "group-hover", "focus-within", "focus"],
    textOpacity: ["responsive", "hover", "dark", "group-hover", "focus-within", "focus"],
    textOverflow: ["responsive", "hover"],
    textTransform: ["responsive", "hover"],
    transform: ["responsive", "hover"],
    transformOrigin: ["responsive", "hover"],
    transitionDelay: ["responsive", "hover"],
    transitionDuration: ["responsive", "hover"],
    transitionProperty: ["responsive", "hover"],
    transitionTimingFunction: ["responsive", "hover"],
    translate: ["responsive", "hover", "focus"],
    userSelect: ["responsive", "hover"],
    verticalAlign: ["responsive", "hover"],
    visibility: ["responsive", "hover"],
    whitespace: ["responsive", "hover"],
    width: ["responsive", "hover"],
    wordBreak: ["responsive", "hover"],
    zIndex: ["responsive", "hover", "focus-within", "focus"]
  }
};
